[advisories]
ignore = [
    "RUSTSEC-2023-0071",  # RSA Marvin Attack - affects sqlx-mysql which we don't use
]

informational_warnings = ["unmaintained"]  # Warn about unmaintained crates but don't fail
